FROM node:hydrogen-alpine3.16 as builder

WORKDIR /home/node/app

COPY . .

RUN yarn install

RUN yarn build

# FROM node:hydrogen-alpine3.16

# WORKDIR /home/node/app

# RUN npm install -g http-server

# COPY --from=builder /home/node/app/dist .

# EXPOSE 8080

# CMD [ "http-server", "." ]

FROM node:hydrogen-alpine3.16

WORKDIR /home/node/app

COPY --from=builder /home/node/app/dist .