version: '3'

services:

  app:
    build: .
    tty: true
    container_name: app
    entrypoint: ./entrypoint.sh
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules